// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "store-backend",
    "version": "1"
  },
  "paths": {
    "/products": {
      "get": {
        "summary": "getProducts",
        "description": "",
        "operationId": "getProducts.get.products",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "products",
            "schema": {
              "$ref": "#/definitions/ProductsResponse"
            }
          },
          "502": {
            "description": "server error"
          }
        }
      },
      "post": {
        "summary": "createProduct",
        "description": "",
        "operationId": "createProduct.post.products",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "product",
            "schema": {
              "$ref": "#/definitions/ProductsResponse"
            }
          },
          "502": {
            "description": "server error"
          }
        }
      }
    },
    "/products/{id}": {
      "get": {
        "summary": "getProduct",
        "description": "",
        "operationId": "getProduct.get.products/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "product",
            "schema": {
              "$ref": "#/definitions/ProductResponse"
            }
          },
          "404": {
            "description": "product not found",
            "schema": {
              "$ref": "#/definitions/NotFound"
            }
          },
          "502": {
            "description": "server error"
          }
        }
      }
    },
    "/import": {
      "get": {
        "summary": "importProductsFile",
        "description": "",
        "operationId": "importProductsFile.get.import",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "file",
            "schema": {
              "$ref": "#/definitions/SignedUrl"
            }
          },
          "502": {
            "description": "Server error"
          }
        }
      }
    }
  },
  "definitions": {
    "Product": {
      "properties": {
        "id": {
          "title": "Product.id",
          "type": "string"
        },
        "title": {
          "title": "Product.title",
          "type": "string"
        },
        "description": {
          "title": "Product.description",
          "type": "string"
        },
        "price": {
          "title": "Product.price",
          "type": "number"
        },
        "image": {
          "title": "Product.image",
          "type": "string"
        }
      },
      "required": [
        "id",
        "title",
        "description",
        "price"
      ],
      "additionalProperties": false,
      "title": "Product",
      "type": "object"
    },
    "ProductResponse": {
      "properties": {
        "data": {
          "$ref": "#/definitions/Product",
          "title": "ProductResponse.data"
        },
        "message": {
          "title": "ProductResponse.message",
          "enum": [
            "product"
          ],
          "type": "string"
        }
      },
      "required": [
        "data",
        "message"
      ],
      "additionalProperties": false,
      "title": "ProductResponse",
      "type": "object"
    },
    "Products": {
      "items": {
        "$ref": "#/definitions/Product",
        "title": "Products.[]"
      },
      "title": "Products.[]",
      "type": "array"
    },
    "ProductsResponse": {
      "properties": {
        "data": {
          "$ref": "#/definitions/Products",
          "title": "ProductsResponse.data"
        },
        "message": {
          "title": "ProductsResponse.message",
          "enum": [
            "products"
          ],
          "type": "string"
        }
      },
      "required": [
        "data",
        "message"
      ],
      "additionalProperties": false,
      "title": "ProductsResponse",
      "type": "object"
    },
    "SignedUrl": {
      "properties": {
        "data": {
          "properties": {
            "signedUrl": {
              "title": "SignedUrl.data.signedUrl",
              "type": "string"
            }
          },
          "required": [
            "signedUrl"
          ],
          "additionalProperties": false,
          "title": "SignedUrl.data",
          "type": "object"
        },
        "message": {
          "title": "SignedUrl.message",
          "enum": [
            "signed url"
          ],
          "type": "string"
        }
      },
      "required": [
        "data",
        "message"
      ],
      "additionalProperties": false,
      "title": "SignedUrl",
      "type": "object"
    },
    "NotFound": {
      "properties": {
        "message": {
          "title": "NotFound.message",
          "enum": [
            "Not Found"
          ],
          "type": "string"
        }
      },
      "required": [
        "message"
      ],
      "additionalProperties": false,
      "title": "NotFound",
      "type": "object"
    }
  },
  "securityDefinitions": {}
};