// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "store-backend",
    "version": "1"
  },
  "paths": {
    "/products": {
      "get": {
        "summary": "getProducts",
        "description": "",
        "operationId": "getProducts.get.products",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "products",
            "schema": {
              "$ref": "#/definitions/Products"
            }
          },
          "502": {
            "description": "server error"
          }
        }
      }
    },
    "/products/{id}": {
      "get": {
        "summary": "getProduct",
        "description": "",
        "operationId": "getProduct.get.products/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "product",
            "schema": {
              "$ref": "#/definitions/Product"
            }
          },
          "404": {
            "description": "product not found",
            "schema": {
              "$ref": "#/definitions/ProductNotFound"
            }
          },
          "502": {
            "description": "server error"
          }
        }
      }
    }
  },
  "definitions": {
    "Product": {
      "properties": {
        "id": {
          "title": "Product.id",
          "type": "string"
        },
        "title": {
          "title": "Product.title",
          "type": "string"
        },
        "description": {
          "title": "Product.description",
          "type": "string"
        },
        "price": {
          "title": "Product.price",
          "type": "number"
        },
        "image": {
          "title": "Product.image",
          "type": "string"
        }
      },
      "required": [
        "id",
        "title",
        "description",
        "price"
      ],
      "additionalProperties": false,
      "title": "Product",
      "type": "object"
    },
    "Products": {
      "items": {
        "$ref": "#/definitions/Product",
        "title": "Products.[]"
      },
      "title": "Products.[]",
      "type": "array"
    },
    "ProductNotFound": {
      "title": "ProductNotFound",
      "enum": [
        "Product not found"
      ],
      "type": "string"
    }
  },
  "securityDefinitions": {},
  "host": "sk3bwmuscd.execute-api.us-east-1.amazonaws.com/dev"
};